// backend/functions/files/src/services/pdfService.js
// PDF Generation Service for Kundli Reports - FIXED VERSION

const PDFDocument = require('pdfkit');
const logger = require('../utils/logger');

/**
 * Generate Kundli PDF report
 * @param {Object} data - { birthDetails, chartData, userName }
 * @returns {Promise<Buffer>} PDF buffer
 */
const generateKundliPDF = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const { birthDetails, chartData, userName } = data;

      logger.info('Starting PDF generation', {
        service: 'pdfService',
        userName: userName || 'Unknown'
      });

      // Create PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        info: {
          Title: `Kundli - ${userName}`,
          Author: 'AstroAI',
          Subject: 'Vedic Birth Chart'
        }
      });

      const buffers = [];
      
      // Collect PDF data
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        logger.info('PDF generated successfully', {
          service: 'pdfService',
          size: pdfBuffer.length
        });
        resolve(pdfBuffer);
      });

      doc.on('error', (err) => {
        logger.error('PDF generation error', {
          service: 'pdfService',
          error: err.message
        });
        reject(err);
      });

      // --- PDF CONTENT ---

      // 1. HEADER
      doc.fontSize(24)
         .fillColor('#4A148C')
         .text('VEDIC BIRTH CHART', { align: 'center' });
      
      doc.moveDown(0.5);
      doc.fontSize(10)
         .fillColor('#666')
         .text(`Generated by AstroAI on ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });
      
      doc.moveDown(2);

      // 2. BIRTH DETAILS
      doc.fontSize(16)
         .fillColor('#4A148C')
         .text('Birth Information');
      
      doc.moveDown(0.5);
      
      const birthInfo = [
        ['Name:', birthDetails.name || userName || 'User'],
        ['Date of Birth:', birthDetails.dateOfBirth ? new Date(birthDetails.dateOfBirth).toLocaleDateString('en-IN') : 'N/A'],
        ['Time of Birth:', birthDetails.timeOfBirth || 'N/A'],
        ['Place of Birth:', birthDetails.placeOfBirth || 'N/A'],
        ['Coordinates:', birthDetails.latitude && birthDetails.longitude ? 
          `${parseFloat(birthDetails.latitude).toFixed(4)}°N, ${parseFloat(birthDetails.longitude).toFixed(4)}°E` : 'N/A'],
        ['Timezone:', birthDetails.timezone || 'N/A']
      ];

      doc.fontSize(12).fillColor('#000');
      birthInfo.forEach(([label, value]) => {
        doc.font('Helvetica-Bold').text(label, { continued: true })
           .font('Helvetica').text(` ${value}`);
        doc.moveDown(0.3);
      });

      doc.moveDown(1.5);

      // 3. PLANETARY POSITIONS
      doc.fontSize(16)
         .fillColor('#4A148C')
         .text('Planetary Positions');
      
      doc.moveDown(0.5);

      if (chartData?.planets && chartData.planets.length > 0) {
        doc.fontSize(11).fillColor('#000');
        
        // Table header
        doc.font('Helvetica-Bold');
        const tableTop = doc.y;
        doc.text('Planet', 70, tableTop, { width: 100 });
        doc.text('Sign', 200, tableTop, { width: 100 });
        doc.text('Degree', 330, tableTop, { width: 100 });
        doc.text('House', 450, tableTop, { width: 50 });
        
        doc.moveDown(0.8);
        doc.moveTo(70, doc.y).lineTo(520, doc.y).stroke();
        doc.moveDown(0.3);

        // Planet rows
        doc.font('Helvetica');
        chartData.planets.forEach((planet) => {
          const yPos = doc.y;
          doc.text(planet.name || 'N/A', 70, yPos, { width: 100 });
          doc.text(planet.sign || 'N/A', 200, yPos, { width: 100 });
          doc.text(planet.degree || 'N/A', 330, yPos, { width: 100 });
          doc.text(planet.house?.toString() || 'N/A', 450, yPos, { width: 50 });
          doc.moveDown(0.6);
        });
      } else {
        doc.fontSize(11)
           .fillColor('#666')
           .text('Planetary data not available');
      }

      doc.moveDown(2);

      // 4. HOUSE CUSPS (if available)
      if (chartData?.houses && chartData.houses.length > 0) {
        // Check if we need a new page
        if (doc.y > 650) {
          doc.addPage();
        }

        doc.fontSize(16)
           .fillColor('#4A148C')
           .text('House Cusps');
        
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#000');

        chartData.houses.forEach((house, index) => {
          doc.text(`House ${index + 1}: ${house.sign || 'N/A'} (${house.degree ? house.degree.toFixed(2) + '°' : 'N/A'})`);
          doc.moveDown(0.3);
        });

        doc.moveDown(1.5);
      }

      // 5. ASCENDANT & SPECIAL POINTS
      if (chartData?.ascendant) {
        doc.fontSize(16)
           .fillColor('#4A148C')
           .text('Special Points');
        
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor('#000');

        doc.font('Helvetica-Bold').text('Ascendant (Lagna): ', { continued: true })
           .font('Helvetica').text(chartData.ascendant.sign || 'N/A');
        
        if (chartData.ascendant.degree) {
          doc.text(`Degree: ${chartData.ascendant.degree.toFixed(2)}°`);
        }

        doc.moveDown(1.5);
      }

      // 6. FOOTER
      doc.fontSize(9)
         .fillColor('#999')
         .text('This is a computer-generated Kundli. For detailed analysis, consult with an expert astrologer.', {
           align: 'center'
         });
      
      doc.moveDown(0.5);
      doc.text('© 2024 AstroAI. All rights reserved.', { align: 'center' });

      // Finalize PDF
      doc.end();

    } catch (error) {
      logger.error('PDF generation failed', {
        service: 'pdfService',
        error: error.message,
        stack: error.stack
      });
      reject(error);
    }
  });
};

module.exports = {
  generateKundliPDF
};